export const AlbumActionTypes = {
    FETCH_ALBUMS_PENDING: 'FETCH_ALBUMS_PENDING',
    FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',
    FETCH_ALBUM: 'FETCH_ALBUM',
    FETCH_ALBUMS_ERROR: 'FETCH_ALBUMS_ERROR'
}
