export const ArtistActionTypes = {
    FETCH_ARTIST_PENDING: 'FETCH_ARTIST_PENDING',
    FETCH_ARTIST_SUCCESS: 'FETCH_ARTIST_SUCCESS',
    FETCH_ARTIST_ERROR: 'FETCH_ARTIST_ERROR',
    FETCH_ARTISTS_SUCCESS: 'FETCH_ARTISTS_SUCCESS',
    GET_AUDIO_DETAILS: 'GET_AUDIO_DETAILS'
}